### ISSUE TITLE
auto message function

### ISSUE THREAD

**Issue by 20dec** [fmohican/YoshinonBot#1]
Hi,

Not a issue, just ask for code for auto notice function. If I have a value get from json link, then the value reach the number i wanted (for example: 0), bot auto message to room "ZERO". Is it possible?

Thanks
20dec

**Comment by fmohican** [comment]
Hmm like auto announcer ? its possible... i just need to think how xD ...
I will think about that and i will reply back if i got something :)

**Comment by fmohican** [comment]
@20dec soon will push update to github with auto message function.

**Comment by 20dec** [comment]
Glad to hear that. Will wait for seeing. Thanks

**Comment by fmohican** [comment]
@20dec done.
If you have more enchantments please tell me xD

**Comment by 20dec** [comment]
"room.message" in "onConnect" in "class bot(ch.RoomManager)" in ch.py
can you help me to make room.message possible use anywhere in python code, as a global command?

**Comment by fmohican** [comment]
Hmm... you can't.... try to make as function....

**Comment by 20dec** [comment]
for example code like this: 

```
def doWork():
    while True:
        print("Working...")
        with urllib.request.urlopen("http://api-link") as url:
            api = json.loads(url.read().decode())
            value = api['number']
        print(value)
        if (value== 0):
            print(api)
            room.message("ZERO")
        time.sleep(5)
if __name__ == "__main__":
    p = Process(target=doWork)
    p.start()
    bot.easy_start(rooms,username,password)
    while True:
        time.sleep(30)   
```

**Comment by 20dec** [comment]
edit code in code quote

**Comment by 20dec** [comment]
my problem, I cannot use room.message at there. but if i def onConnect or onMessage. it don't work too

**Comment by fmohican** [comment]
Hm.
I have no ideea.
Better ask on https://stackoverflow.com/ , i'm 100% sure you will got an answer.

**Comment by 20dec** [comment]
Thanks for your response at all 👍
